#!/bin/sh

# POST CHECKOUT = git checkout

exec < /dev/tty

printf "\n"
printf "\033[1;33m[NOTICE]\033[0;37m\n"
printf "\n"
printf " Below are the list of names with designated code.\n"
printf " e.g., <designated-code> = <name>\n"
printf "\n"
printf " \033[1;35m[DEV]\033[0;37m\n"
printf "  D1 = John Doe\n"
printf "  D2 = Sam Doe\n"
printf "\n"

is_passed_codename="0"
executed_by=""
codename=""

while [ "$is_passed_codename" != "1" ]; do 
    if [ "$codename" = "D1" ]; then
        is_passed_codename="1"
        executed_by="John Doe"
        break;
    
    elif [ "$codename" = "D2" ]; then
        is_passed_codename="1"
        executed_by="Sam Doe"
        break;
    fi 
    read -p "Please give your name based on the designated code: " codename
done

current_build="$2"
current_branch="$(git branch | grep \* | cut -d ' ' -f2)"
checkout_output="$(git reflog | sed -n 1p | cut -d ':' -f3)";

body="
{
\"text\": \"*Git Activity on <Server> (192.168.x.x)*
*Executed By:* $executed_by
*Affected Path:* $(pwd)
*Command:* 'git checkout $current_branch'
*Build Number*: $current_build
\n
$checkout_output
\"
}
"

curl -s -X POST \
-H 'Content-type: application/json' \
--data "$body" \
'https://hooks.slack.com/services/XXXXXXX/XXXXXXX/XXXXXXX' -o /dev/null
